models:
  - name: stg_payments
    description: Staging model applying light transformations to source data
    columns:
      - name: payment_id
        description: A unique key identifying each payment
        tests:
          - unique
          - not_null
      - name: transactionTime
        description: The timestamp for when the payment was completed
        tests:
          - not_null
      - name: transactionMonth
        description: The month on which the payment was completed, represented by the first day of the month
        tests:
          - not_null

  - name: int_payments_periodised
    description: Intermediate model that splits payment data evenly across months
    columns:
      - name: active_from
        description: The first month on which the payment contributes to MRR
        tests:
          - not_null
      - name: active_to
        description: The last month on which the payment contributes to MRR
        tests:
          - not_null
      - name: amount_periodised
        description: The monthly equivalent amount that a payment contributes to MRR
        tests:
          - not_null

  - name: int_dim_months
    description: A dimension model containing a date series with the month starts between 2015 and 2018
    columns:
      - name: metric_month
        description: The date of the first date in each month
        tests:
          - not_null
          - unique

  - name: int_monthly_subs
    description: Intermediate model that contains, for every month, each user/subscription that was active on that month, together with the periodised monthly revenue

  - name: int_monthly_subs_leadlag
    description: This model elaborates on int_monthly_subs by including information about the each customer's subscription in the month before and after the current period.
    columns:
      - name: product_lead
        description: The product that the user was subscribed to on the month before the current period
      - name: amount_periodised_lead
        description: The monthly equivalent amount that a payment contributed to MRR on the month before the current period
      - name: product_lag
        description: The product that the user was subscribed to on the month after the current period
      - name: amount_periodised_lag
        description: The monthly equivalent amount that a payment contributed to MRR on the month after the current period


  - name: metric_mrr
    description: Metric model that indicates the monthly recurring revenue and number of monthly subscribers by country and subscription type
    columns:
      - name: metric_month
        description: The month for which MRR is being calculated
        tests:
          - not_null
      - name: billingCountry
        description: A dimension segmenting the metric across countries
        tests:
          - not_null
      - name: product
        description: A dimension segmenting the metric across subscription products
        tests:
          - not_null
      - name: active_subscribers
        description: The number of users with a subscription active on a particular month
        tests:
          - not_null
      - name: mrr
        description: The monthly equivalent revenue (MRR) from subscriptions active on a given month
        tests:
          - not_null

  - name: metric_churn
    description: Metric model that calculates the subscriber base (value/volume) at the beginning of each month, and how much subscriber base (value/volume) was retained during the month. These metrics can be used to calculate churn rates.
    columns:
      - name: churn_month
        description: The month for which churn rates are being calculated
        tests:
          - not_null
      - name: product
        description: A dimension to enable calculating churn rates separately by subscription product
        tests:
          - not_null
      - name: billingCountry
        description: A dimension to enable calculating churn rates separately by country
        tests:
          - not_null
      - name: starting_revenue
        description: The total MRR at the beginning of the month, calculated as total MRR from the previous month
        tests:
          - not_null
      - name: starting_customers
        description: The total number of subscribed users at the beginning of the month, calculated as total number of subscribed users from the previous month
        tests:
          - not_null
      - name: retained_revenue
        description: The total MRR retained from existing customers, calculated as MRR from customers also active on the previous month
        tests:
          - not_null
      - name: retained_customers
        description: The total number of subscribed users retained from existing customers, calculated as the number of subscribed users that were also active on the previous month
        tests:
          - not_null

  - name: metric_acquisitions
    description: Metric model that calculates the monthly number of newly acquired customers, and compares it with the customer base size and cancellations
    columns:
      - name: customers_acquired
        description: The number of customers that were subscribed in a month, which were not subscribed on the previous month
        tests:
          - not_null
      - name: cancelled_customers
        description: The number of subscribers that were subscribed on the previous month but are no longer subscribed
      - name: customer_base
        description: The total number of subscribers on the previous month

  - name: metric_monthly_subs
    description: Metric model that aggregates monthly subscribers and calculated the monthly number of subscribers and revenue for each product and country
    columns:
      - name: no_customers
        description: The number of customers that were subscribed in a month for a given product and country
      - name: mrr
        description: The total periodised revenue in a month for a given product and country        